[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "common.*",
    "slack.*", 
    "router",
    "boto3.*"
]
ignore_missing_imports = true

