# ステージング環境設定
# このファイルはステージング環境の設定を定義します

environment:
  name: staging
  url: https://staging-api.example.com  # 実際のステージングURLに更新してください

# 環境固有の変数
variables:
  AWS_REGION: ap-northeast-1
  ENVIRONMENT: staging
  LOG_LEVEL: DEBUG

# 保護ルール（オプション）
protection_rules:
  required_reviewers: 1
  wait_timer: 0  # ステージングでは待機時間なし
